### ISSUE TITLE
KbuildCrawler does not checkout commits without a commit hash correctly

### ISSUE THREAD

**Issue by Elscha** [SSE-LinuxAnalysis/KbuildCrawler#1]
Example test case:
```
url:    https://github.com/0day-ci/linux/commits/Marek-Szyprowski/phy-exynos-mipi-video-simplify-check-for-coupled-phy-status/20160802-170240
base:   https://git.kernel.org/pub/scm/linux/kernel/git/kishon/linux-phy.git next
```
Will checkout the current version (from 2018) but not the tested version (from 2016).
If now commit hash is provided in mail, please use date of mail for a checkout, e.g., for the respective mail:
``git checkout --force `git rev-list -n 1 --before="2016-08-02 17:31:03" next` ``

More information at https://stackoverflow.com/a/6990682

**Comment by adam-sse** [comment]
991ac2dd5dcded56197d0742eb420dbca29689a6
